import { StyleSheet } from "react-native";
import { TOKENS } from "../../../constants/tokens";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: TOKENS.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: TOKENS.border,
    backgroundColor: TOKENS.card,
    gap: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitleWrapper: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: TOKENS.dark,
    lineHeight: 20,
  },
  headerSubtitle: {
    fontSize: 11,
    color: TOKENS.muted,
    marginTop: 2,
    lineHeight: 14,
  },
  headerActionsWrapper: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  headerTextBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TOKENS.lightBlue,
    borderWidth: 1,
    borderColor: TOKENS.accentBlue,
    paddingHorizontal: 12,
    borderRadius: 19,
    gap: 4,
    height: 38,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: TOKENS.lightBlue,
    borderWidth: 1,
    borderColor: TOKENS.accentBlue,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTextBtnDisabled: {
    opacity: 0.8,
  },
  headerTextBtnLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: TOKENS.primary,
    lineHeight: 14,
  },
  scrollContent: {
    padding: 16,
    gap: 16,
  },
  periodPillsRow: {
    flexDirection: "row",
    backgroundColor: "#F1F5F9", // modern light slate background
    borderRadius: 14,
    padding: 4,
    gap: 2,
  },
  periodPill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  periodPillActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  periodPillText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#64748B",
  },
  periodPillTextActive: {
    color: TOKENS.primary,
    fontWeight: "bold",
  },
  loadingContainer: {
    paddingVertical: 80,
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    fontSize: 12,
    color: TOKENS.muted,
    fontWeight: "600",
  },
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  kpiCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TOKENS.border,
    padding: 14,
    gap: 6,
  },
  kpiIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  kpiLabel: {
    fontSize: 11,
    color: TOKENS.muted,
    fontWeight: "600",
  },
  kpiValue: {
    fontSize: 16,
    fontWeight: "800",
    color: TOKENS.dark,
  },
  chartWrapper: {
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TOKENS.border,
    padding: 16,
    gap: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  barGraphRow: {
    flexDirection: "row",
    height: 140,
    alignItems: "flex-end",
    justifyContent: "space-around",
    paddingTop: 10,
  },
  barGraphCol: {
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  barTrack: {
    width: 14,
    height: 100,
    backgroundColor: "#F3F4F6",
    borderRadius: 7,
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  barFill: {
    width: "100%",
    backgroundColor: TOKENS.primary,
    borderRadius: 7,
  },
  barLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: TOKENS.muted,
  },
  seederContainer: {
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TOKENS.border,
    padding: 24,
    alignItems: "center",
    gap: 12,
  },
  seederText: {
    fontSize: 12,
    color: TOKENS.muted,
    textAlign: "center",
    lineHeight: 16,
  },
  seederBtn: {
    backgroundColor: TOKENS.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  seederBtnText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
  },
  syncDatabaseSection: {
    marginTop: 16,
    gap: 8,
    alignItems: "center",
  },
  syncDatabaseBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TOKENS.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: "100%",
  },
  syncDatabaseBtnText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
  },
  syncDatabaseHelpText: {
    fontSize: 11,
    color: TOKENS.muted,
    textAlign: "center",
    lineHeight: 15,
    paddingHorizontal: 24,
  },
  statsSection: {
    gap: 12,
  },
  statsCardList: {
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TOKENS.border,
    paddingVertical: 6,
  },
  statListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  rankCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  rankGold: { backgroundColor: "#FBBF24" },
  rankSilver: { backgroundColor: "#9CA3AF" },
  rankBronze: { backgroundColor: "#F59E0B" },
  rankText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#fff",
  },
  statItemName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: TOKENS.dark,
  },
  statItemQty: {
    fontSize: 11,
    color: TOKENS.muted,
    marginRight: 16,
  },
  statItemRevenue: {
    fontSize: 13,
    fontWeight: "700",
    color: TOKENS.dark,
  },
  exportSection: {
    gap: 12,
  },
  exportButtonsRow: {
    flexDirection: "row",
    gap: 12,
  },
  exportCardBtn: {
    flex: 1,
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    gap: 6,
    alignItems: "flex-start",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  exportPdfCard: {
    borderColor: "#FECDD3", // soft red
    backgroundColor: "#FFF5F5",
  },
  exportCsvCard: {
    borderColor: "#A7F3D0", // soft emerald
    backgroundColor: "#F0FDF4",
  },
  exportIconBadgePdf: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFE4E6",
    alignItems: "center",
    justifyContent: "center",
  },
  exportIconBadgeCsv: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
  },
  exportPdfTextTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#991B1B",
  },
  exportCsvTextTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#065F46",
  },
  exportCardSubtitle: {
    fontSize: 10,
    color: TOKENS.muted,
    fontWeight: "500",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "flex-end",
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  datePickerContent: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: TOKENS.card,
    borderRadius: 24,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: TOKENS.border,
    padding: 20,
    gap: 16,
  },
  calendarHeaderNavigation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F1F5F9",
    borderRadius: 12,
    padding: 6,
    marginBottom: 4,
  },
  calendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  calendarMonthYearLabel: {
    fontSize: 13,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  calendarPresetsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 6,
    marginBottom: 4,
  },
  calendarPresetPill: {
    flex: 1,
    height: 30,
    backgroundColor: TOKENS.lightBlue,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: TOKENS.accentBlue,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarPresetPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: TOKENS.primary,
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: TOKENS.dark,
    textAlign: "center",
    marginBottom: 4,
  },
  weekdaysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  weekdayLabel: {
    width: 38,
    textAlign: "center",
    fontSize: 11,
    fontWeight: "bold",
    color: TOKENS.muted,
  },
  daysGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 8,
  },
  emptyDayCell: {
    width: 38,
    height: 38,
  },
  dayCell: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCellInRange: {
    backgroundColor: "#EFF6FF",
    borderRadius: 0,
  },
  dayCellSelectedStart: {
    backgroundColor: TOKENS.primary,
    borderRadius: 19,
  },
  dayCellSelectedEnd: {
    backgroundColor: TOKENS.primary,
    borderRadius: 19,
  },
  dayText: {
    fontSize: 12,
    fontWeight: "600",
    color: TOKENS.dark,
  },
  dayTextInRange: {
    color: TOKENS.primary,
  },
  dayTextSelected: {
    color: "#fff",
    fontWeight: "bold",
  },
  selectedDatesPreview: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginTop: 6,
  },
  previewLabel: {
    fontSize: 11,
    fontWeight: "bold",
    color: TOKENS.muted,
  },
  previewValue: {
    fontSize: 11,
    fontWeight: "bold",
    color: TOKENS.primary,
  },
  lowStockModalContent: {
    backgroundColor: TOKENS.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    maxHeight: "80%",
  },
  lowStockModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  lowStockModalTitleWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  lowStockModalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  closeLowStockBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  lowStockModalSubtitle: {
    fontSize: 12,
    color: TOKENS.muted,
    lineHeight: 16,
    marginBottom: 12,
  },
  lowStockItemsScroll: {
    flexGrow: 0,
  },
  lowStockItemRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TOKENS.border,
    padding: 12,
    gap: 12,
  },
  lowStockIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FCE8E6",
    alignItems: "center",
    justifyContent: "center",
  },
  lowStockItemName: {
    fontSize: 13,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  lowStockItemSku: {
    fontSize: 11,
    color: TOKENS.muted,
    marginTop: 1,
  },
  lowStockCountBadge: {
    alignItems: "flex-end",
    gap: 2,
  },
  lowStockCountText: {
    fontSize: 12,
    fontWeight: "bold",
    color: TOKENS.error,
  },
  lowStockLimitText: {
    fontSize: 9,
    color: TOKENS.muted,
    fontWeight: "500",
  },
  emptyLowStockState: {
    paddingVertical: 40,
    alignItems: "center",
    gap: 12,
  },
  emptyLowStockText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#10B981",
  },
  textInput: {
    height: 46,
    backgroundColor: TOKENS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: TOKENS.border,
    paddingHorizontal: 14,
    fontSize: 13,
    color: TOKENS.dark,
  },
  modalButtonsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
  },
  modalCancelBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: {
    fontSize: 13,
    color: TOKENS.muted,
    fontWeight: "bold",
  },
  modalConfirmBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: TOKENS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmBtnText: {
    fontSize: 13,
    color: "#fff",
    fontWeight: "bold",
  },
  exportProgressCard: {
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    gap: 12,
  },
  exportProgressText: {
    fontSize: 12,
    color: TOKENS.muted,
    fontWeight: "600",
  },
  exportResultCard: {
    backgroundColor: TOKENS.background,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    alignItems: "center",
    gap: 16,
  },
  dragHandle: {
    width: 40,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "#E5E7EB",
    alignSelf: "center",
    marginBottom: 8,
  },
  successIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#10B981",
    alignItems: "center",
    justifyContent: "center",
  },
  successTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  successSubtitle: {
    fontSize: 12,
    color: TOKENS.muted,
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 16,
  },
  successActions: {
    width: "100%",
    gap: 12,
    marginTop: 10,
  },
  shareReportBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    backgroundColor: TOKENS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  shareReportBtnText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
  },
  dismissBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  dismissBtnText: {
    fontSize: 13,
    color: TOKENS.muted,
    fontWeight: "bold",
  },
  modalTabsRow: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 4,
    marginBottom: 10,
  },
  modalTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  modalTabActive: {
    backgroundColor: TOKENS.card,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  modalTabText: {
    fontSize: 12,
    fontWeight: "600",
    color: TOKENS.muted,
  },
  modalTabTextActive: {
    color: TOKENS.primary,
    fontWeight: "bold",
  },
  historyOrderCard: {
    backgroundColor: TOKENS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TOKENS.border,
    marginBottom: 10,
    overflow: "hidden",
  },
  historyCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 8,
  },
  historyInvoiceNum: {
    fontSize: 13,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  historyDateText: {
    fontSize: 10,
    color: TOKENS.muted,
    marginTop: 2,
  },
  historyTotalAmount: {
    fontSize: 13,
    fontWeight: "800",
    color: TOKENS.dark,
  },
  historyItemCount: {
    fontSize: 10,
    color: TOKENS.muted,
    fontWeight: "500",
  },
  historyItemsExpandedPanel: {
    paddingHorizontal: 8,
    paddingBottom: 8,
    backgroundColor: "#FAFAFA",
  },
  expandedDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginBottom: 8,
  },
  expandedItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  expandedItemName: {
    flex: 1.5,
    fontSize: 12,
    fontWeight: "600",
    color: TOKENS.dark,
  },
  expandedItemQty: {
    flex: 1.2,
    fontSize: 11,
    color: TOKENS.muted,
    textAlign: "right",
    paddingRight: 10,
  },
  expandedItemSubtotal: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: TOKENS.dark,
    textAlign: "right",
  },
  refillSectionLabel: {
    fontSize: 11,
    color: TOKENS.muted,
    marginBottom: 10,
    fontWeight: "600",
  },
  refillCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 14,
    paddingLeft: 3,
    paddingTop: 3,
    paddingBottom: 3,
    gap: 12,
  },
  refillProductImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
  },
  refillProductName: {
    fontSize: 14,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  refillProductMeta: {
    fontSize: 11,
    color: TOKENS.muted,
    marginTop: 2,
  },
  refillStockCount: {
    fontSize: 13,
    fontWeight: "700",
    color: TOKENS.dark,
  },
  refillInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 42,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: TOKENS.border,
    borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 4,
  },
  refillInputInline: {
    flex: 1,
    height: "100%",
    fontSize: 13,
    color: TOKENS.dark,
    padding: 0,
  },
  refillSubmitBtnInline: {
    height: 34,
    backgroundColor: TOKENS.success,
    borderRadius: 8,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  refillSubmitBtnInlineText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  refillInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  refillCurrentStockLabel: {
    fontSize: 12,
    color: TOKENS.muted,
    fontWeight: "500",
  },
  refillCurrentStockValue: {
    fontSize: 13,
    color: TOKENS.dark,
    fontWeight: "bold",
  },
  absoluteCloseBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  premiumModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  premiumModalContainer: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: TOKENS.card,
    borderRadius: 24,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: TOKENS.border,
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  premiumModalHeader: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: TOKENS.border,
    gap: 4,
  },
  premiumModalScroll: {
    flex: 1,
  },
  premiumModalScrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 8,
  },
  premiumModalFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: TOKENS.border,
    backgroundColor: TOKENS.card,
    gap: 6,
  },
  pdfModalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
    paddingRight: 24,
  },
  pdfModalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  pdfModalDescription: {
    fontSize: 11,
    color: TOKENS.muted,
    lineHeight: 15,
  },
  pdfOptionsList: {
    gap: 8,
  },
  pdfOptionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: TOKENS.border,
    borderRadius: 14,
    padding: 10,
    gap: 10,
  },
  pdfOptionCardSelected: {
    borderColor: TOKENS.primary,
    backgroundColor: TOKENS.lightBlue,
  },
  pdfOptionIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  pdfOptionTextCol: {
    flex: 1,
    gap: 1,
  },
  pdfOptionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: TOKENS.dark,
  },
  pdfOptionDesc: {
    fontSize: 10,
    color: TOKENS.muted,
    lineHeight: 13,
  },
  pdfOptionRadio: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: TOKENS.muted,
    alignItems: "center",
    justifyContent: "center",
  },
  pdfOptionRadioSelected: {
    borderColor: TOKENS.primary,
  },
  pdfOptionRadioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: TOKENS.primary,
  },
  pdfGenerateBtn: {
    height: 44,
    borderRadius: 12,
    backgroundColor: TOKENS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pdfGenerateBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "bold",
  },
  pdfCancelBtn: {
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  pdfCancelBtnText: {
    color: TOKENS.muted,
    fontSize: 12,
    fontWeight: "bold",
  },
});
