// Centralized seed products for restaurant-focused demo data
// Use stable image URLs (picsum.photos by id) to avoid 404s from hotlinked images
export const SEEDING_PRODUCTS = [
  {
    name: "Margherita Pizza",
    price: 850,
    category: "pizza",
    icon: "https://picsum.photos/id/1080/800/600",
    stockCount: 12,
    unitType: "Pieces",
    costPrice: 450,
    quickCode: "2001",
  },
  {
    name: "Chicken Biryani",
    price: 780,
    category: "rice",
    icon: "https://picsum.photos/id/292/800/600",
    stockCount: 20,
    unitType: "Plates",
    costPrice: 420,
    quickCode: "2002",
  },
  {
    name: "Beef Burger",
    price: 560,
    category: "burgers",
    icon: "https://picsum.photos/id/292/800/600",
    stockCount: 18,
    unitType: "Pieces",
    costPrice: 300,
    quickCode: "2003",
  },
  {
    name: "Caesar Salad",
    price: 420,
    category: "salads",
    icon: "https://picsum.photos/id/1025/800/600",
    stockCount: 10,
    unitType: "Bowls",
    costPrice: 220,
    quickCode: "2004",
  },
  {
    name: "Spaghetti Carbonara",
    price: 690,
    category: "pasta",
    icon: "https://picsum.photos/id/1081/800/600",
    stockCount: 14,
    unitType: "Plates",
    costPrice: 360,
    quickCode: "2005",
  },
  {
    name: "Grilled Salmon",
    price: 1200,
    category: "main",
    icon: "https://picsum.photos/id/292/800/600",
    stockCount: 8,
    unitType: "Plates",
    costPrice: 800,
    quickCode: "2006",
  },
  {
    name: "Chicken Fried Rice",
    price: 480,
    category: "rice",
    icon: "https://picsum.photos/id/1062/800/600",
    stockCount: 25,
    unitType: "Plates",
    costPrice: 260,
    quickCode: "2007",
  },
  {
    name: "Crispy Chicken Wings",
    price: 390,
    category: "snacks",
    icon: "https://picsum.photos/id/292/800/600",
    stockCount: 30,
    unitType: "Plates",
    costPrice: 210,
    quickCode: "2008",
  },
  {
    name: "Veggie Wrap",
    price: 320,
    category: "wraps",
    icon: "https://picsum.photos/id/1082/800/600",
    stockCount: 22,
    unitType: "Pieces",
    costPrice: 150,
    quickCode: "2009",
  },
  {
    name: "Chocolate Brownie",
    price: 220,
    category: "dessert",
    icon: "https://picsum.photos/id/1083/800/600",
    stockCount: 40,
    unitType: "Pieces",
    costPrice: 90,
    quickCode: "2010",
  },
];

export default SEEDING_PRODUCTS;
