import { StyleSheet } from 'react-native';
import { TOKENS } from '../../constants/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: TOKENS.background,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  toastContainer: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    backgroundColor: TOKENS.dark,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 8,
    zIndex: 999,
    boxShadow: '0px 2px 4px 0px rgba(0, 0, 0, 0.15)',
    maxWidth: '90%',
  },
  toastText: {
    color: TOKENS.card,
    fontSize: 13,
    fontWeight: '600',
  },
  brandingWrapper: {
    alignItems: 'center',
    marginBottom: 32,
    gap: 6,
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  logoSquare: {
    width: 68,
    height: 68,
    borderRadius: 18,
    backgroundColor: TOKENS.accentBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    boxShadow: `0px 6px 8px 0px ${TOKENS.primary}4D`,
  },
  logoImage: {
    width: 90,
    height: 90,
    borderRadius: 18,
  },
  appName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: TOKENS.dark,
    letterSpacing: 0.5,
  },
  appTagline: {
    fontSize: 12,
    color: TOKENS.muted,
  },
  card: {
    backgroundColor: TOKENS.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: TOKENS.border,
    padding: 24,
    boxShadow: '0px 10px 16px 0px rgba(0, 0, 0, 0.04)',
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: TOKENS.dark,
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: 13,
    color: TOKENS.muted,
    lineHeight: 18,
    marginBottom: 20,
  },
  inputLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: TOKENS.dark,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  hintMarker: {
    fontSize: 11,
    color: TOKENS.primary,
    fontWeight: '600',
  },
  phoneInputRow: {
    flexDirection: 'row',
    height: 48,
    borderWidth: 1,
    borderColor: TOKENS.border,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#F9FAFB',
    marginBottom: 20,
  },
  countryCodeBox: {
    paddingHorizontal: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: TOKENS.border,
  },
  countryCodeText: {
    fontSize: 14,
    fontWeight: '600',
    color: TOKENS.dark,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 12,
    color: TOKENS.dark,
    fontWeight: '600',
  },
  otpContainer: {
    width: '100%',
    position: 'relative',
    height: 54,
    marginBottom: 24,
    justifyContent: 'center',
  },
  hiddenOtpInput: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0,
    zIndex: 10,
  },
  otpSlotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
  },
  otpSlotBox: {
    width: 46,
    height: 50,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: TOKENS.border,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpSlotBoxFilled: {
    borderColor: TOKENS.primary,
    backgroundColor: TOKENS.card,
  },
  otpSlotBoxFocused: {
    borderColor: TOKENS.primary,
    borderWidth: 2,
    backgroundColor: TOKENS.card,
  },
  otpSlotBoxError: {
    borderColor: TOKENS.error,
    backgroundColor: '#FDF2F2',
  },
  otpSlotText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: TOKENS.dark,
  },
  otpSlotTextError: {
    color: TOKENS.error,
  },
  submitButton: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: TOKENS.primary,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  submitButtonShadow: {
    boxShadow: `0px 4px 6px 0px ${TOKENS.primary}33`,
  },
  submitButtonDisabled: {
    backgroundColor: '#E5E7EB',
  },
  submitButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: TOKENS.card,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  backBtnText: {
    fontSize: 13,
    color: TOKENS.primary,
    fontWeight: '600',
  },
  formGroup: {
    gap: 6,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: TOKENS.dark,
  },
  formInput: {
    height: 44,
    borderWidth: 1,
    borderColor: TOKENS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    color: TOKENS.dark,
    backgroundColor: '#F9FAFB',
    fontWeight: '500',
  },
  formInputDisabled: {
    backgroundColor: '#F3F4F6',
    color: TOKENS.muted,
  },
  onboardingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    marginTop: 8,
  },
  progressBarBg: {
    flex: 1,
    height: 6,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    marginRight: 16,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: TOKENS.primary,
    borderRadius: 3,
  },
  stepIndicatorText: {
    fontSize: 14,
    fontWeight: '700',
    color: TOKENS.primary,
  },
  onboardingTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: TOKENS.dark,
    lineHeight: 30,
    marginBottom: 8,
  },
  onboardingSubtitle: {
    fontSize: 13,
    color: TOKENS.muted,
    lineHeight: 18,
    marginBottom: 24,
  },
  premiumInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    borderWidth: 1.5,
    borderColor: TOKENS.border,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 16,
    marginBottom: 32,
  },
  premiumInputWrapperFocused: {
    borderColor: TOKENS.primary,
    backgroundColor: TOKENS.card,
    boxShadow: `0px 4px 8px 0px ${TOKENS.primary}14`,
  },
  premiumTextInput: {
    flex: 1,
    height: '100%',
    fontSize: 15,
    color: TOKENS.dark,
    fontWeight: '600',
  },
  inputCheckmark: {
    marginLeft: 10,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 32,
  },
  chipBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: TOKENS.border,
    backgroundColor: TOKENS.card,
    gap: 8,
  },
  chipBoxSelected: {
    borderColor: TOKENS.primary,
    backgroundColor: '#EFF6FF',
  },
  chipEmoji: {
    fontSize: 15,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: TOKENS.dark,
  },
  chipTextSelected: {
    color: TOKENS.primary,
  },
  chipCheck: {
    marginLeft: 2,
  },
  premiumNextBtn: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: TOKENS.primary,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  premiumNextBtnShadow: {
    boxShadow: `0px 4px 6px 0px ${TOKENS.primary}33`,
  },
  premiumNextBtnDisabled: {
    backgroundColor: '#E5E7EB',
  },
  premiumNextBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: TOKENS.card,
  },
});
